# vim: set ft=sh:
# shellcheck shell=sh
#
# https://www.shellcheck.net/wiki/SC2154
# shellcheck disable=2154

[ "$break" = luks ] && { print "break before luks.init"; sh; }

mkdir -p /run/cryptsetup

resolve_device "$luks_root"

DM_DISABLE_UDEV=1 cryptsetup open \
    "${luks_discard:+--allow-discards}" \
    "${luks_header:+--header=$luks_header}" \
    "${luks_key:+--key-file=$luks_key}" -- "$device" \
    "${luks_name:-crypt-${device##*/}}" || panic "failed to unlock LUKS"
