#!/bin/sh
#
# false positive
# shellcheck disable=2154

for _mod in cdrom loop overlay squashfs; do
    copy_module "$_mod"
done

for _bin in blockdev cp losetup umount; do
    copy_binary "$_bin"
done
